version: "3"
services:
  base:
    image: pgedge-base
    build:
      context: pgedge-base
      args:
        PGUSER: postgres
        # github branch version of spock
        #   v3.1.1 has a compile error against pg16 against EvalPlanQualInit
        #SPOCK_BRANCH: v3.1.1
        SPOCK_BRANCH: main
        # Choose 15 or 16
        PG_MAJOR_VERSION: 16
    deploy:
      # one wierd trick for creating a base image to use below
      # but not actually start any containers with this service
      mode: replicated
      replicas: 0
  writer:
    build:
      context: pgedge-writer
      args:
        PGDATABASE: test
        PGUSER: postgres
    deploy:
      mode: replicated
      replicas: 3
  reader:
    build:
      context: pgedge-reader
      args:
        PGDATABASE: test
        PGUSER: postgres
    deploy:
      mode: replicated
      replicas: 3
      #  pgcat2:
# TODO:
# * read only replicas
# * pgcat2 load balancer
# * pgmanage web UI
